[package]
name = "forge_select"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
console.workspace = true
cliclack.workspace = true
derive_setters.workspace = true

crossterm.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
