[package]
name = "forge_template"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]

convert_case.workspace = true
html-escape = "0.2.13"

[dev-dependencies]
insta.workspace = true
pretty_assertions.workspace = true
