[package]
name = "forge_template"
version = "0.1.0"
edition = "2024"

[dependencies]

html-escape = "0.2.13"
handlebars = "6.3.2"
colored = "3.0.0"
serde_json = "1.0.145"

[dev-dependencies]
pretty_assertions.workspace = true
