[package]
name = "forge_snaps"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
forge_fs.workspace = true

forge_domain.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time", "test-util"] }
tempfile.workspace = true